export const postgresWriteOperations = [
  {
    name: 'createOrder',
    route: 'POST /api/orders',
    transaction: true,
    tables: ['orders', 'order_extras', 'order_status_logs', 'payments', 'availability_slots'],
    steps: [
      'select activity_pricings and availability_slots for update',
      'validate availability_slots.status = available',
      'insert orders with status pending_payment',
      'insert selected order_extras',
      'insert payments with status pending',
      'update availability_slots to locked with locked_order_id',
      'insert order_status_logs',
    ],
  },
  {
    name: 'markPaymentPaid',
    route: 'POST /api/payments/:paymentId/mock-success and POST /api/payments/wechat/notify',
    transaction: true,
    tables: ['payments', 'orders', 'availability_slots', 'conversations', 'order_status_logs'],
    steps: [
      'select payments and related orders for update',
      'validate payment.status = pending and order.status = pending_payment',
      'update payments to paid',
      'update orders to paid_pending_confirm and set paid_at',
      'update availability_slots to booked',
      'insert conversations if missing',
      'insert order_status_logs',
    ],
  },
  {
    name: 'setAdminOrderStatus',
    route: 'POST /api/admin/orders/:orderId/status',
    transaction: true,
    tables: ['orders', 'order_status_logs', 'settlements', 'companion_wallets', 'ledger_entries'],
    steps: [
      'select orders for update',
      'update orders to admin selected status',
      'insert order_status_logs with admin operator',
      'insert settlements, companion_wallets, and ledger_entries when admin marks completed',
      'mirror admin_action_logs through audit gateway',
    ],
  },
  {
    name: 'transitionOrder',
    route: 'POST /api/orders/:orderId/:action',
    transaction: true,
    tables: ['orders', 'order_status_logs', 'availability_slots', 'settlements', 'companion_wallets', 'ledger_entries', 'refunds'],
    steps: [
      'select orders for update',
      'validate role permission and allowed status transition',
      'update orders to next status',
      'insert order_status_logs',
      'release availability_slots on cancel when applicable',
      'insert settlements, companion_wallets, ledger_entries, or refunds when applicable',
    ],
  },
  {
    name: 'sendMessage',
    route: 'POST /api/conversations/:conversationId/messages',
    transaction: true,
    tables: ['conversations', 'messages', 'message_risk_events'],
    steps: [
      'select conversations with related order access context',
      'evaluate content against risk_keywords',
      'insert clean or flagged messages',
      'insert message_risk_events for flagged or blocked content',
      'update conversations.last_message_at',
    ],
  },
  {
    name: 'createReport',
    route: 'POST /api/orders/:orderId/report',
    transaction: true,
    tables: ['reports', 'audit_cases'],
    steps: ['select orders for report context', 'insert reports', 'insert linked audit_cases for moderation queue'],
  },
  {
    name: 'applyModerationAction',
    route: 'POST /api/admin/moderation/:caseId/actions',
    transaction: true,
    tables: ['message_risk_events', 'reports', 'admin_action_logs', 'orders', 'conversations'],
    steps: [
      'select risk/report case for update',
      'insert admin_action_logs',
      'update case status',
      'apply side effect such as restrict_chat or freeze_order',
    ],
  },
  {
    name: 'reviewAuditCase',
    route: 'POST /api/admin/audit-cases/:caseId/approve or reject',
    transaction: true,
    tables: ['audit_cases', 'audit_logs', 'admin_action_logs', 'companions', 'posts', 'reports'],
    steps: [
      'select audit_cases for update',
      'update audit_cases review status and reviewer',
      'insert audit_logs and admin_action_logs',
      'sync companion, post, or report target status',
    ],
  },
  {
    name: 'recordAuditTrail',
    route: 'admin audit / admin action boundary',
    transaction: true,
    tables: ['audit_logs', 'admin_action_logs'],
    steps: [
      'insert audit_logs for manual review decisions',
      'insert admin_action_logs for sensitive admin operations',
      'preserve before_data and after_data snapshots for rollback review',
    ],
  },
  {
    name: 'recordSecurityEvent',
    route: 'permission boundary / auth guard',
    transaction: true,
    tables: ['security_events'],
    steps: [
      'build security event from denied session and target context',
      'insert security_events with event_type permission_denied or login anomaly',
      'preserve metadata for later risk review and abuse detection',
    ],
  },
  {
    name: 'manageSession',
    route: 'auth login / logout / session guard',
    transaction: true,
    tables: ['user_sessions'],
    steps: [
      'create user or admin session with exactly one actor owner',
      'touch active session on trusted authenticated requests',
      'revoke session on logout or security invalidation',
    ],
  },
  {
    name: 'upsertAuthIdentityUser',
    route: 'POST /api/auth/wechat/login',
    transaction: true,
    tables: ['users', 'user_auth_identities'],
    steps: [
      'lock auth identity by provider and provider_user_id',
      'create user and identity when this is the first login',
      'update last_login_at for returning identities',
    ],
  },
];

export function getPostgresWriteOperation(name) {
  return postgresWriteOperations.find((operation) => operation.name === name);
}
