export const postgresWriteOperations = [
  {
    name: 'createOrder',
    route: 'POST /api/orders',
    transaction: true,
    tables: ['idempotency_keys', 'orders', 'order_extras', 'order_status_logs', 'payments', 'availability_slots'],
    steps: [
      'begin idempotency key for actor-scoped create order request',
      'select activity_pricings and availability_slots for update',
      'validate availability_slots.status = available',
      'insert orders with status pending_payment',
      'insert selected order_extras',
      'insert payments with status pending',
      'update availability_slots to locked with locked_order_id',
      'insert order_status_logs',
      'complete idempotency key with cached response after successful order creation',
    ],
  },
  {
    name: 'recordProviderCallback',
    route: 'POST /api/payments/wechat/notify and POST /api/payments/wechat/refund-notify',
    transaction: true,
    tables: ['provider_callback_events'],
    steps: [
      'record raw provider callback event before business status mutation',
      'dedupe by provider, event type, and provider event id',
      'mark processed after the payment or refund transaction succeeds',
      'mark retrying or failed when callback processing cannot be completed',
    ],
  },
  {
    name: 'markPaymentPaid',
    route: 'POST /api/payments/:paymentId/mock-success and POST /api/payments/wechat/notify',
    transaction: true,
    tables: ['provider_callback_events', 'payments', 'orders', 'availability_slots', 'conversations', 'order_status_logs'],
    steps: [
      'select payments and related orders for update',
      'return success without side effects when payment is already paid',
      'validate payment.status = pending and order.status = pending_payment',
      'update payments to paid',
      'update orders to paid_pending_confirm and set paid_at',
      'update availability_slots to booked',
      'insert conversations if missing',
      'insert order_status_logs',
    ],
  },
  {
    name: 'markPaymentTerminal',
    route: 'POST /api/payments/wechat/notify for CLOSED, REVOKED, and PAYERROR',
    transaction: true,
    tables: ['provider_callback_events', 'payments'],
    steps: [
      'select payments for update',
      'return success without side effects when payment is no longer pending',
      'update pending payments to closed or failed',
      'store raw callback for payment audit trail',
    ],
  },
  {
    name: 'setAdminOrderStatus',
    route: 'POST /api/admin/orders/:orderId/status',
    transaction: true,
    tables: ['orders', 'order_status_logs', 'settlements', 'companion_wallets', 'ledger_entries'],
    steps: [
      'select orders for update',
      'update orders to admin selected status',
      'insert order_status_logs with admin operator',
      'insert settlements, companion_wallets, and ledger_entries when admin marks completed',
      'mirror admin_action_logs through audit gateway',
    ],
  },
  {
    name: 'transitionOrder',
    route: 'POST /api/orders/:orderId/:action',
    transaction: true,
    tables: ['idempotency_keys', 'orders', 'order_status_logs', 'availability_slots', 'settlements', 'companion_wallets', 'ledger_entries', 'refunds'],
    steps: [
      'check completed actor-scoped idempotency key before status validation',
      'begin idempotency key after status validation',
      'select orders for update',
      'return success without side effects when the transition was already applied',
      'validate role permission and allowed status transition',
      'update orders to next status',
      'insert order_status_logs',
      'release availability_slots on cancel when applicable',
      'insert settlements, companion_wallets, ledger_entries, or refunds when applicable',
      'complete idempotency key with cached response after successful transition',
    ],
  },
  {
    name: 'markRefundTerminal',
    route: 'refund provider callback / refund processing job',
    transaction: true,
    tables: ['provider_callback_events', 'refunds', 'orders', 'order_status_logs'],
    steps: [
      'select refunds and linked orders for update',
      'return success without side effects when refund is already terminal',
      'update refunds to succeeded, failed, or rejected with raw callback',
      'update refunding orders to refunded when refund succeeds',
      'insert order_status_logs when order reaches refunded',
    ],
  },
  {
    name: 'expirePendingPayments',
    route: 'scheduled payment timeout job',
    transaction: true,
    tables: ['orders', 'payments', 'availability_slots', 'order_status_logs'],
    steps: [
      'select expired pending_payment orders with locked slots for update skip locked',
      'close pending payments without touching already paid payments',
      'cancel expired orders with timeout reason',
      'release locked availability_slots',
      'insert order_status_logs for the automatic cancellation',
    ],
  },
  {
    name: 'sendMessage',
    route: 'POST /api/conversations/:conversationId/messages',
    transaction: true,
    tables: ['conversations', 'messages', 'message_risk_events'],
    steps: [
      'select conversations with related order access context',
      'evaluate content against risk_keywords',
      'insert clean or flagged messages',
      'insert message_risk_events for flagged or blocked content',
      'update conversations.last_message_at',
    ],
  },
  {
    name: 'createReport',
    route: 'POST /api/orders/:orderId/report',
    transaction: true,
    tables: ['reports', 'audit_cases'],
    steps: ['select orders for report context', 'insert reports', 'insert linked audit_cases for moderation queue'],
  },
  {
    name: 'applyModerationAction',
    route: 'POST /api/admin/moderation/:caseId/actions',
    transaction: true,
    tables: ['message_risk_events', 'reports', 'admin_action_logs', 'orders', 'conversations'],
    steps: [
      'select risk/report case for update',
      'insert admin_action_logs',
      'update case status',
      'apply side effect such as restrict_chat or freeze_order',
    ],
  },
  {
    name: 'reviewAuditCase',
    route: 'POST /api/admin/audit-cases/:caseId/approve or reject',
    transaction: true,
    tables: ['audit_cases', 'audit_logs', 'admin_action_logs', 'companions', 'posts', 'reports'],
    steps: [
      'select audit_cases for update',
      'update audit_cases review status and reviewer',
      'insert audit_logs and admin_action_logs',
      'sync companion, post, or report target status',
    ],
  },
  {
    name: 'recordAuditTrail',
    route: 'admin audit / admin action boundary',
    transaction: true,
    tables: ['audit_logs', 'admin_action_logs'],
    steps: [
      'insert audit_logs for manual review decisions',
      'insert admin_action_logs for sensitive admin operations',
      'preserve before_data and after_data snapshots for rollback review',
    ],
  },
  {
    name: 'recordSecurityEvent',
    route: 'permission boundary / auth guard',
    transaction: true,
    tables: ['security_events'],
    steps: [
      'build security event from denied session and target context',
      'insert security_events with event_type permission_denied or login anomaly',
      'preserve metadata for later risk review and abuse detection',
    ],
  },
  {
    name: 'manageSession',
    route: 'auth login / logout / session guard',
    transaction: true,
    tables: ['user_sessions'],
    steps: [
      'create user or admin session with exactly one actor owner',
      'touch active session on trusted authenticated requests',
      'revoke session on logout or security invalidation',
    ],
  },
  {
    name: 'upsertAuthIdentityUser',
    route: 'POST /api/auth/wechat/login',
    transaction: true,
    tables: ['users', 'user_auth_identities'],
    steps: [
      'lock auth identity by provider and provider_user_id',
      'create user and identity when this is the first login',
      'update last_login_at for returning identities',
    ],
  },
];

export function getPostgresWriteOperation(name) {
  return postgresWriteOperations.find((operation) => operation.name === name);
}
